const img = {
  facePack: "https://ik.imagekit.io/hliyltsjxz/orgo/face-pack.jpg",
  lemonBar: "https://ik.imagekit.io/hliyltsjxz/orgo/lemon-bar.jpg",
  roseBar: "https://ik.imagekit.io/hliyltsjxz/orgo/rose-bar.jpg",
  barsPackaged: "https://ik.imagekit.io/hliyltsjxz/orgo/bars-packaged.jpg",
  collection: "https://ik.imagekit.io/hliyltsjxz/orgo/collection.jpg",
  howToUse: "https://ik.imagekit.io/hliyltsjxz/orgo/how-to-use.jpg",
  lid: "https://ik.imagekit.io/hliyltsjxz/orgo/lid.jpg",
};

export const products = [
  {
    slug: "signature-face-pack",
    name: "Signature Face Pack Pouch",
    size: "50g",
    price: 199,
    badge: "BESTSELLER",
    category: "Face Care",
    type: "Face Masks",
    concerns: ["Acne", "Tan", "Dullness"],
    short: "Deep cleansing face pack for a naturally radiant glow.",
    description:
      "Deeply cleanses dirt and excess oil, fights acne and blemishes, fades sun tan for a radiant glow. Perfect for all skin types.",
    benefits: [
      "Deep cleansing",
      "Helps fight acne & blemishes",
      "Helps reduce appearance of tan",
      "Suitable for all skin types",
    ],
    ingredients:
      "Natural face pack powder blend of farm-fresh botanical herbs, rose petals and clay. No parabens. No artificial fragrances.",
    howToUse:
      "Mix the required amount with water or rose water into a smooth paste. Apply an even layer, leave for 8–10 minutes, gently scrub and rinse.",
    suitableFor: "All skin types. For external use only. Patch test recommended.",
    image: img.facePack,
    gallery: [img.facePack, img.lid, img.howToUse, img.collection],
    inStock: true,
    featured: true,
  },
  {
    slug: "lemon-scrub-bar",
    name: "Lemon Scrub Bar",
    size: "90g × 2",
    price: 299,
    eachNote: "₹150 each",
    category: "Body Care",
    type: "Scrub Bars",
    concerns: ["Dullness", "Dry Skin"],
    short: "Refreshing loofa scrub bar with natural lemon extracts.",
    description:
      "Deeply exfoliates dead skin, refreshes and energizes the body, and supports healthy-looking skin with natural lemon extracts.",
    benefits: [
      "Deep exfoliation with natural loofa",
      "Refreshes and energizes",
      "Natural lemon extracts",
      "Handcrafted in small batches",
    ],
    ingredients: "Cold-pressed lemon extracts, natural loofa, glycerin soap base, farm-fresh botanicals.",
    howToUse: "Lather on damp skin, massage in circular motions, rinse well. Store in a dry soap dish.",
    suitableFor: "Normal to oily skin. For external use only.",
    image: img.lemonBar,
    gallery: [img.lemonBar, img.barsPackaged, img.collection],
    inStock: true,
    featured: true,
  },
  {
    slug: "rose-scrub-bar",
    name: "Rose Scrub Bar",
    size: "90g × 2",
    price: 299,
    eachNote: "₹150 each",
    category: "Body Care",
    type: "Scrub Bars",
    concerns: ["Dry Skin", "Dullness"],
    short: "Softening rose bar with a luxurious natural fragrance.",
    description:
      "Softens and smooths skin, deeply moisturizes with a luxurious rose fragrance, and promotes a supple, glowing complexion.",
    benefits: [
      "Softens and smooths skin",
      "Deeply moisturizing",
      "Luxurious natural rose fragrance",
      "Handcrafted with dried rose petals",
    ],
    ingredients: "Dried rose petals, rose extract, natural loofa, glycerin soap base.",
    howToUse: "Lather on damp skin, massage gently, rinse well. Follow with a moisturizer.",
    suitableFor: "All skin types, especially dry skin. For external use only.",
    image: img.roseBar,
    gallery: [img.roseBar, img.barsPackaged, img.collection],
    inStock: true,
    featured: true,
  },
  {
    slug: "d-tan-coffee-bar",
    name: "D-Tan Coffee Bar",
    size: "90g × 2",
    price: 299,
    eachNote: "₹150 each",
    badge: "POPULAR",
    category: "Body Care",
    type: "Scrub Bars",
    concerns: ["Tan", "Acne", "Pigmentation"],
    short: "Coffee bar that targets the look of tan and dark spots.",
    description:
      "Helps reduce the appearance of acne and pigmentation, targets the look of stubborn tan and dark spots, and supports naturally brighter-looking skin.",
    benefits: [
      "Targets the look of stubborn tan",
      "Helps with the appearance of dark spots",
      "Supports brighter-looking skin",
      "Natural coffee grounds for gentle scrub",
    ],
    ingredients: "Roasted coffee grounds, natural botanicals, glycerin soap base.",
    howToUse: "Lather on damp skin, massage in circular motions for 1–2 minutes, rinse well.",
    suitableFor: "All skin types. For external use only. Patch test recommended.",
    image: img.barsPackaged,
    gallery: [img.barsPackaged, img.collection, img.lid],
    inStock: true,
    featured: true,
  },
];

export const curations = [
  {
    slug: "bronze-essential-trio",
    tier: "Bronze",
    title: "Essential Trio",
    label: "IDEAL FOR BEGINNERS",
    items: ["Tan Remover Soap Bar", "Face Mask", "Hair / Beard Oil"],
    price: 649,
    cta: "SHOP BRONZE",
  },
  {
    slug: "silver-head-to-toe",
    tier: "Silver",
    title: "Head-to-Toe Care",
    label: "ADVANCED WELLNESS",
    items: [
      "2 Tan Remover Bars",
      "Lime Body Scrub Loofa Bar",
      "Face Mask",
      "Hair / Beard Oil",
      "Hydrating Rose Mist",
    ],
    price: 1249,
    cta: "SHOP SILVER",
  },
  {
    slug: "gold-ultimate-luxury",
    tier: "Gold",
    title: "Ultimate Luxury",
    label: "PURE INDULGENCE",
    items: [
      "Tan Remover Soap Bar",
      "Rose Body Scrub Bar",
      "Face Mask",
      "Detox Mask",
      "Hair / Beard Oil",
      "Premium Travel Pouch",
    ],
    price: 1899,
    cta: "SHOP GOLD",
  },
];
